### ISSUE TITLE
Шиза в прогрессбаре

### ISSUE THREAD

**Issue by nekonya3031** [Leyn-pl/durkasell.ru#1]
при состоянии 96/100 и других при добавлении в данном случае более 4х очков все что больше 4х уезжает в дурку. :not_owlonks:

**Comment by Leyn-pl** [comment]
Пофиг но попробую что-нибудь сделать

**Comment by Leyn-pl** [comment]
Это не ошибка. Это загрузка и тут так и должно быть (да да конечно)

**Comment by nekonya3031** [comment]
слился по факту
